(function(){
"use strict";
const PRODUCTS={
 "butch-birthday-donkey": {id:"butch-birthday-donkey",title:"Birthday Donkey — Where Is My Cake?",artist:"Ernest Lee “Butch” Breger",brand:"The Ernest Lee \"Butch The Barn Man\" Breger Museum",image:"https://shareshuffle.com/merch/butch/birthday-donkey-gray.png",localImage:"/merch/butch/birthday-donkey-gray.png",status:"live",merchant:"Amazon Merch on Demand",asin:"B0H968Y4DP",destinationUrl:"https://www.amazon.com/dp/B0H968Y4DP",rightsStatus:"approved",mockupNote:"Illustrative mockup. Actual garment color, scale and print may vary.",description:"Butch's hand-drawn birthday donkey, preserved with the original lettering and refrigerator-art character."},
 "butch-movie-star-dog": {id:"butch-movie-star-dog",title:"Movie Star Dog — I Do Not Fetch a Stick",artist:"Ernest Lee “Butch” Breger",brand:"The Ernest Lee \"Butch The Barn Man\" Breger Museum",image:"https://shareshuffle.com/merch/butch/movie-star-dog-yellow.png",localImage:"/merch/butch/movie-star-dog-yellow.png",status:"live",merchant:"Amazon Merch on Demand",asin:"B0H98Q41TW",destinationUrl:"https://www.amazon.com/dp/B0H98Q41TW",rightsStatus:"approved",mockupNote:"Illustrative mockup. Actual garment color, scale and print may vary.",description:"A cowboy movie-star dog who knows fetching is somebody else's job, including the original $5 sticker."},
 "butch-mirror-pig": {id:"butch-mirror-pig",title:"Mirror Pig — Go Look in the Mirror",artist:"Ernest Lee “Butch” Breger",brand:"The Ernest Lee \"Butch The Barn Man\" Breger Museum",image:"https://shareshuffle.com/merch/butch/mirror-pig-red.png",localImage:"/merch/butch/mirror-pig-red.png",status:"live",merchant:"Amazon Merch on Demand",asin:"B0H96JQMF9",destinationUrl:"https://www.amazon.com/dp/B0H96JQMF9",rightsStatus:"approved",mockupNote:"Illustrative mockup. Actual garment color, scale and print may vary.",description:"Butch's wonderfully blunt mirror-gazing pig, reproduced from the Rich Williams Collection."},
 "butch-museum-shop": {id:"butch-museum-shop",type:"collection",title:"The Butch Breger Museum Shop",artist:"Ernest Lee “Butch” Breger",brand:"The Ernest Lee \"Butch The Barn Man\" Breger Museum",image:"https://shareshuffle.com/merch/butch/movie-star-dog-yellow.png",localImage:"/merch/butch/movie-star-dog-yellow.png",images:["https://shareshuffle.com/merch/butch/birthday-donkey-gray.png","https://shareshuffle.com/merch/butch/movie-star-dog-yellow.png","https://shareshuffle.com/merch/butch/mirror-pig-red.png"],status:"live",merchant:"Amazon Merch on Demand",destinationUrl:"https://www.amazon.com/s/ref=bl_sl_s_ap_web_7141123011?ie=UTF8&node=7141123011&field-brandtextbin=The+Ernest+Lee+%22Butch+The+Barn+Man%22+Breger+Museum",rightsStatus:"approved",mockupNote:"Three approved Amazon Merch on Demand designs from the Rich Williams Collection.",description:"Shop all approved Butch Breger Museum shirts on Amazon in one place."}
};
const SCRIPT=document.currentScript;
const BASE=new URL(SCRIPT?.src||"https://shareshuffle.com/embed.js").origin;
function esc(s){return String(s||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function amazonLink(url){const a=window.ShuffleLinkCheck?.analyze(url,{pageHost:location.hostname});return a?.suggestedUrl||url}
function mount(el){const id=el.dataset.product||"";const p=PRODUCTS[id]||{title:el.dataset.title,image:el.dataset.image,destinationUrl:el.dataset.url,status:el.dataset.status||"live",description:el.dataset.description||""};if(!p.title)return;
 const layout=el.dataset.layout||"standard";const pending=p.status!=="live";const href=amazonLink(p.destinationUrl||"");const disclosure=window.ShuffleLinkCheck?.disclosure(window.ShuffleLinkCheck?.analyze(href,{pageHost:location.hostname}))||"";
 const media=Array.isArray(p.images)&&p.images.length?`<div class="ss-collage">${p.images.map((src,index)=>`<img loading="lazy" src="${esc(src)}" alt="${esc(p.title)} design ${index+1}">`).join("")}</div>`:`<img loading="lazy" src="${esc(p.image||p.localImage)}" alt="${esc(p.title)} shirt mockup">`;
 el.classList.add("ss-product-embed",`ss-layout-${layout}`,p.type==="collection"?"ss-product-collection":"ss-product-item");el.innerHTML=`<article>${media}<div class="ss-copy"><span class="ss-kicker">${pending?"Amazon review in progress":p.type==="collection"?"The complete approved collection":"Available through Amazon"}</span><h3>${esc(p.title)}</h3><p>${esc(p.description||"")}</p><p class="ss-note">${esc(p.mockupNote||"")}</p><a class="ss-button" href="${esc(href)}" target="_blank" rel="sponsored noopener">${pending?"Check Amazon brand page":p.type==="collection"?"Shop all three on Amazon":"View on Amazon"}</a>${disclosure?`<small>${esc(disclosure)}</small>`:""}</div></article>`;
}
function css(){if(document.getElementById("ss-embed-css"))return;const s=document.createElement("style");s.id="ss-embed-css";s.textContent=`.ss-product-embed{font-family:system-ui,-apple-system,sans-serif;color:#171717}.ss-product-embed article{display:grid;grid-template-columns:minmax(160px,42%) 1fr;gap:20px;align-items:center;background:#fffaf0;border:1px solid #d8c9ad;border-radius:22px;padding:16px;box-shadow:0 12px 36px #2b1c0c1a}.ss-product-embed img{display:block;width:100%;max-height:420px;object-fit:contain;border-radius:15px;background:#eee}.ss-collage{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.ss-collage img{height:190px;border-radius:10px}.ss-product-embed h3{margin:.3rem 0;font-size:clamp(1.25rem,3vw,2rem)}.ss-product-embed p{line-height:1.45}.ss-kicker{font-size:.76rem;text-transform:uppercase;letter-spacing:.08em;font-weight:900;color:#8c2b25}.ss-note,.ss-product-embed small{display:block;font-size:.76rem;color:#625b50}.ss-button{display:inline-flex;background:#181613;color:white!important;text-decoration:none;border-radius:999px;padding:11px 16px;font-weight:900;margin:7px 0}.ss-layout-compact article{grid-template-columns:105px 1fr;padding:11px;border-radius:16px}.ss-layout-compact p{display:none}.ss-layout-compact img{height:125px}.ss-layout-feature article{grid-template-columns:1fr 1fr;background:linear-gradient(135deg,#fff7d7,#fff)}.ss-product-collection article{grid-template-columns:1.25fr .75fr;background:linear-gradient(135deg,#fff7d7,#fff)}@media(max-width:620px){.ss-product-embed article,.ss-layout-feature article,.ss-product-collection article{grid-template-columns:1fr}.ss-collage img{height:150px}}`;document.head.appendChild(s)}
function init(){css();document.querySelectorAll("[data-shuffle-product]").forEach(el=>{el.dataset.product=el.dataset.shuffleProduct;mount(el)})}
if(!window.ShuffleLinkCheck){const l=document.createElement("script");l.src=BASE+"/assets/link-check.js";l.onload=init;document.head.appendChild(l)}else init();
window.ShuffleProductEmbeds={products:PRODUCTS,mount};
})();
