import test from 'node:test';import assert from 'node:assert/strict';import {preparePlaylist} from '../functions/src/automation.js';
const make=()=>({songs:['a','b','c'].map(id=>({songId:id,title:id,inPlaylist:true,canonical:null})),playlistDirty:true});
const candidate=id=>({videoId:id,title:'Live',channel:'Artist',score:110,eligible:true});
test('new invited set picks strong matches and publishes automatically',async()=>{const p=make();let count=0;await preparePlaylist(p,{search:async s=>[candidate(s.songId)],saveCanonical:async(_id,c)=>{assert.equal(c.selection,'automatic');count++;},sync:async()=> 'playlist',save:async()=>{}});assert.equal(count,3);assert.equal(p.playlistId,'playlist');assert.equal(p.automation.state,'ready');assert.equal(p.playlistDirty,false);});
test('no eligible live match blocks publishing and names the song needing review',async()=>{const p=make();await preparePlaylist(p,{search:async()=>[{...candidate('x'),eligible:false}],saveCanonical:async()=>assert.fail(),sync:async()=>assert.fail(),save:async()=>{}});assert.equal(p.automation.state,'needs-review');assert.ok(p.automation.message.includes('a, b, c'));});
test('saved owner choices are reused; unchanged playlist is not rewritten',async()=>{const p=make();p.playlistId='existing';p.playlistDirty=false;p.songs.forEach(s=>s.canonical={videoId:s.songId,selection:'owner'});await preparePlaylist(p,{search:async()=>assert.fail(),saveCanonical:async()=>assert.fail(),sync:async()=>assert.fail(),save:async()=>{}});assert.equal(p.automation.state,'ready');assert.equal(p.playlistId,'existing');});
test('set changes trigger update while preserving owner picks',async()=>{const p=make();p.playlistId='existing';p.songs[0].canonical={videoId:'preferred',selection:'owner'};let videos;await preparePlaylist(p,{search:async s=>[candidate(s.songId)],saveCanonical:async()=>{},sync:async plan=>{videos=plan.songs.map(s=>s.canonical.videoId);return 'existing';},save:async()=>{}});assert.deepEqual(videos,['preferred','b','c']);assert.equal(p.playlistId,'existing');});

test('eligible fallback live recording publishes without demanding owner approval',async()=>{const p=make();await preparePlaylist(p,{search:async s=>[{...candidate(s.songId),score:20}],saveCanonical:async()=>{},sync:async()=> 'automatic',save:async()=>{}});assert.equal(p.playlistId,'automatic');});

test('a new plan reference refreshes automatic choices while owner choices remain fixed',async()=>{const p=make();p.songs.forEach(s=>s.canonical={videoId:'old-'+s.songId,selection:'automatic'});p.songs[0].attachments=[{youtubeId:'new-reference'}];p.songs[1].canonical.selection='owner';p.songs[1].attachments=[{youtubeId:'ignored-reference'}];let searches=0;await preparePlaylist(p,{search:async()=>{searches++;return [candidate('new-reference')];},saveCanonical:async()=>{},sync:async()=> 'playlist',save:async()=>{}});assert.equal(searches,1);assert.equal(p.songs[0].canonical.videoId,'new-reference');assert.equal(p.songs[1].canonical.videoId,'old-b');});
