import test from 'node:test';
import assert from 'node:assert/strict';
import {rankVideos,publicPlan,attachmentInfo,serviceDate,playlistVideos,id,digest,token,youtubeVideoId} from '../functions/src/domain.js';
const song={title:'Gratitude',artist:'Brandon Lake',writers:'Benjamin Hastings'};
test('excludes lyric, studio, tutorial and unrelated performances',()=>{const titles=['Gratitude (Live)','Gratitude Live Lyrics','Gratitude Studio','Gratitude live tutorial','Gratitude live cover','Gratitude visualizer','Other Song (Live)'];assert.deepEqual(rankVideos(song,titles.map((title,i)=>({title,channel:'Brandon Lake',videoId:String(i)}))).map(v=>v.videoId),['0','4']);});
test('songwriter preference beats anonymous live upload',()=>{const r=rankVideos(song,[{title:'Gratitude live',channel:'A band'},{title:'Gratitude live',channel:'Benjamin Hastings'}]);assert.equal(r[0].channel,'Benjamin Hastings');});
test('share DTO strips credentials, private attachment references and nested secrets',()=>{const p={id:'p',date:'2026-09-20',title:'Sunday',credential:'SECRET',songs:[{id:'1',songId:'2',title:'Gratitude',canonical:{videoId:'v',title:'live',channel:'artist',refresh_token:'SECRET'},attachments:[{id:'3',name:'chart.pdf',kind:'chart',downloadable:true,resource:'private-api-path',url:'signed-url',keyMatched:true}]}]};const s=publicPlan(p);for(const value of ['SECRET','private-api-path','signed-url'])assert.ok(!JSON.stringify(s).includes(value));assert.equal(s.songs[0].attachments[0].available,false);assert.equal(publicPlan(p,true).songs[0].attachments[0].available,true);});
test('Steven attribution and key match require provider metadata',()=>{const a={id:'1',attributes:{filename:'Steven G.mp3',downloadable:true,allow_mp3_download:true},relationships:{created_by:{data:{id:'steven'}}}};const x=attachmentInfo(a,'arrangement','G','someone-else');assert.equal(x.steven,false);assert.equal(x.keyMatched,false);const y=attachmentInfo(a,'key:G','G','steven');assert.equal(y.steven,true);assert.equal(y.keyMatched,true);});
test('MP3 download restriction honored',()=>assert.equal(attachmentInfo({id:'1',attributes:{filename:'a.mp3',downloadable:true,allow_mp3_download:false}},'item').downloadable,false));
test('service date handles timezone midnight boundary',()=>{assert.equal(serviceDate('2026-09-21T00:30:00Z','America/Chicago'),'2026-09-20');assert.throws(()=>serviceDate('bad'));});
test('playlist requires 3–5 approved selections',()=>{const s=n=>Array.from({length:n},(_,i)=>({canonical:{videoId:String(i)}}));assert.throws(()=>playlistVideos({songs:s(2)}));assert.throws(()=>playlistVideos({songs:s(6)}));assert.deepEqual(playlistVideos({songs:s(3)}),['0','1','2']);assert.throws(()=>playlistVideos({songs:[...s(3),{}]}));});
test('256-bit share token and hashed representation',()=>{const a=token();assert.equal(a.length,43);assert.notEqual(a,token());assert.equal(digest(a).length,64);});
test('invalid document IDs fail closed',()=>{for(const x of ['../secret','a/b','',null])assert.throws(()=>id(x));assert.equal(id('123-456'),'123-456');});

test('writer then Bethel then Hillsong then other live, regardless of views',()=>{const r=rankVideos(song,['Other','Hillsong Worship','Bethel Music','Brandon Lake'].map((channel,i)=>({title:'Gratitude Live',channel,viewCount:10**(9-i)})));assert.deepEqual(r.map(v=>v.channel),['Brandon Lake','Bethel Music','Hillsong Worship','Other']);});
test('older popular live versions win within the same preference tier',()=>{const r=rankVideos(song,[{title:'Gratitude Live',channel:'Other',videoId:'new',publishedAt:'2026-01-01',viewCount:1000},{title:'Gratitude Live',channel:'Other',videoId:'established',publishedAt:'2018-01-01',viewCount:1000000}]);assert.equal(r[0].videoId,'established');});

test('Planning Center linked live versions rank first but studio links remain excluded',()=>{const picks=rankVideos(song,[{title:'Gratitude Live',channel:'Brandon Lake',viewCount:99999999},{title:'Gratitude Live',channel:'Band',planLinked:true},{title:'Gratitude Studio',channel:'Band',planLinked:true}]);assert.equal(picks[0].channel,'Band');assert.equal(picks.length,2);});
test('YouTube link extraction rejects lookalike hosts and nonvideo URLs',()=>{assert.equal(youtubeVideoId('https://youtu.be/MV5x6M38ea8'),'MV5x6M38ea8');assert.equal(youtubeVideoId('https://www.youtube.com/watch?v=MV5x6M38ea8'),'MV5x6M38ea8');assert.equal(youtubeVideoId('https://youtube.com.evil.test/watch?v=MV5x6M38ea8'),null);assert.equal(youtubeVideoId('https://youtube.com/playlist?list=abc'),null);});
