import test from 'node:test';
import assert from 'node:assert/strict';
import {youtube} from '../functions/src/youtube.js';
import {isInvitedSchedule} from '../functions/src/domain.js';
test('wrong channel is rejected before playlist operations',async()=>{const api={channels:{list:async args=>({data:{items:[{id:args.mine?'wrong':'expected'}]}})}};await assert.rejects(youtube(null,api).verifyChannel('expected'),/Choose the YouTube account/);});
test('playlist retry reconciles duplicates and ordering without creating another playlist',async()=>{
 let items=[{id:'i0',snippet:{resourceId:{videoId:'a'},position:0}},{id:'i1',snippet:{resourceId:{videoId:'a'},position:1}},{id:'i2',snippet:{resourceId:{videoId:'old'},position:2}}];let creates=0,seq=10;
 const api={playlists:{insert:async()=>{creates++;return {data:{id:'list'}};},update:async()=>{}},playlistItems:{list:async()=>({data:{items:structuredClone(items)}}),delete:async({id})=>{items=items.filter(x=>x.id!==id);},insert:async({requestBody})=>{items.push({id:String(seq++),snippet:requestBody.snippet});},update:async({requestBody})=>{const i=items.findIndex(x=>x.id===requestBody.id);items[i]=requestBody;}}};
 const plan={date:'2026-09-20',playlistId:'list',songs:['a','b','c'].map(videoId=>({canonical:{videoId}}))};const client=youtube(null,api);await client.sync(plan,()=>assert.fail());await client.sync(plan,()=>assert.fail());assert.equal(creates,0);assert.deepEqual(items.sort((a,b)=>a.snippet.position-b.snippet.position).map(i=>i.snippet.resourceId.videoId),['a','b','c']);
});
test('new playlist ID is saved before adding videos',async()=>{let saved=false;const api={playlists:{insert:async()=>({data:{id:'new'}}),update:async()=>{}},playlistItems:{list:async()=>({data:{items:[]}}),insert:async()=>assert.ok(saved)}};const p={date:'2026-09-20',songs:['a','b','c'].map(videoId=>({canonical:{videoId}}))};assert.equal(await youtube(null,api).sync(p,async value=>{assert.equal(value,'new');saved=true;}),'new');});
test('preparation requires a sent invitation, upcoming visible service and non-declined status',()=>{const s={attributes:{sort_date:'2026-09-20T10:00:00-05:00',plan_visible_to_me:true,status:'U'},relationships:{service_type:{data:{id:'1'}}}};const sent={attributes:{notification_sent_at:'2026-09-17T12:00:00Z'}};const check=(schedule,invitation)=>isInvitedSchedule(schedule,invitation,'1','2026-09-17','America/Chicago');assert.equal(check(s,sent),true);assert.equal(check(s,{attributes:{}}),false);assert.equal(check({...s,attributes:{...s.attributes,status:'D'}},sent),false);assert.equal(check({...s,attributes:{...s.attributes,plan_visible_to_me:false}},sent),false);});
test('first connection resolves the required handle and pins the matching authorized channel',async()=>{const api={channels:{list:async()=>({data:{items:[{id:'personal-channel'}]}})}};const client=youtube(null,api);await assert.rejects(client.verifyChannel(''),/Reconnect/);assert.equal((await client.verifyChannel('',true)).id,'personal-channel');});
test('first connection still rejects a different authorized channel',async()=>{const api={channels:{list:async args=>({data:{items:[{id:args.mine?'other-channel':'personal-channel'}]}})}};await assert.rejects(youtube(null,api).verifyChannel('',true),/Choose the YouTube account/);});

test('search splits writers, includes preferred bands and enriches live results with statistics',async()=>{const queries=[];const api={search:{list:async x=>{queries.push(x.q);return {data:{items:[{id:{videoId:'v'},snippet:{title:'Song',channelTitle:'Writer One'}}]}};}},videos:{list:async()=>({data:{items:[{id:'v',snippet:{title:'Song',channelTitle:'Writer One',description:'Recorded live at the concert',publishedAt:'2015-01-01'},status:{privacyStatus:'public',embeddable:true},statistics:{viewCount:'123456'}}]}})}};const results=await youtube(null,api).alternatives({title:'Song',writers:'Writer One and Writer Two'});assert.equal(results[0].viewCount,123456);assert.equal(results[0].tier,3);assert.ok(queries.some(q=>q.includes('Writer One live')));assert.ok(queries.some(q=>q.includes('Writer Two live')));assert.ok(queries.some(q=>q.includes('Bethel')));assert.ok(queries.some(q=>q.includes('Hillsong')));});
