import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {initializeApp} from 'firebase/app';
import {getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut,connectAuthEmulator} from 'firebase/auth';
import {Music2,Play,RefreshCw,Share2,FileText,Headphones,ArrowUpRight,Check,ChevronRight,X,Settings2,Radio,Link,LogIn,LogOut,CalendarDays,CheckCircle2} from 'lucide-react';
import {demoPlan} from './demo';
import './style.css';
const env=import.meta.env;
const configured=!!env.VITE_FIREBASE_API_KEY;
const auth=configured?getAuth(initializeApp({apiKey:env.VITE_FIREBASE_API_KEY,authDomain:env.VITE_FIREBASE_AUTH_DOMAIN,projectId:env.VITE_FIREBASE_PROJECT_ID,appId:env.VITE_FIREBASE_APP_ID})):null;
if(auth&&env.VITE_USE_EMULATORS==='true')connectAuthEmulator(auth,'http://127.0.0.1:9099');
const shareMatch=location.pathname.match(/^\/(band|service)\/([\w-]+)$/);
const shareKey=location.hash.slice(1);
const dateLabel=d=>new Date(`${d}T12:00:00`).toLocaleDateString('en-US',{month:'long',day:'numeric'});
const positionEmoji=position=>{const p=(position||'').toLowerCase();if(p.includes('leader'))return '🎤';if(p.includes('vocal'))return '🎙️';if(p.includes('acoustic'))return '🪕';if(p.includes('bass'))return '𝄢';if(p.includes('key')||p.includes('piano'))return '🎹';if(p.includes('guitar'))return '🎸';if(p.includes('drum')||p.includes('percussion'))return '🥁';return '🎶';};
function App(){
 const [demo,setDemo]=useState(!configured&&!shareMatch||new URLSearchParams(location.search).has('demo'));
 const [user,setUser]=useState(null),[authReady,setAuthReady]=useState(!auth),[plan,setPlan]=useState(demo?structuredClone(demoPlan):null),[status,setStatus]=useState({}),[plans,setPlans]=useState([]);
 const [busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[panel,setPanel]=useState(null),[alternatives,setAlternatives]=useState([]),[serviceTypes,setServiceTypes]=useState([]),[shares,setShares]=useState([]),[createdLink,setCreatedLink]=useState(''),[artist,setArtist]=useState('');
 const [serviceType,setServiceType]=useState(''),[personId,setPersonId]=useState('');const dialog=useRef(null);const lastRefresh=useRef(0);const previousFocus=useRef(null);
 const readonly=!!shareMatch;
 async function request(path,method='GET',body){const headers={};if(readonly)headers.Authorization=`Share ${shareKey}`;else if(auth?.currentUser)headers.Authorization=`Bearer ${await auth.currentUser.getIdToken()}`;if(body)headers['Content-Type']='application/json';const r=await fetch(`/api${path}`,{method,headers,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not finish. Please try again.');return data;}
 async function run(label,fn){setBusy(label);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy('');}}
 async function load(pid){if(readonly){setPlan(await request(`/shared/${shareMatch[2]}`));return;}const [s,p]=await Promise.all([request('/status'),request('/plans')]);setStatus(s);setServiceType(s.serviceTypeId);setPersonId(s.personId);setPlans(p.plans);const selected=pid||p.currentPlanId;if(selected)setPlan(await request(`/plans/${selected}`));else setPlan(null);}
 async function refresh(){if(demo){setNotice('Sample refreshed. Connect Planning Center to load your real service.');return;}await run('Refreshing',async()=>{lastRefresh.current=Date.now();if(readonly)setPlan(await request(`/shared/${shareMatch[2]}/refresh`,'POST',{}));else{await request('/refresh','POST',{});await load();}setNotice('Up to date with Planning Center.');});}
 useEffect(()=>{if(!auth)return;return onAuthStateChanged(auth,u=>{setUser(u);setAuthReady(true);});},[]);
 useEffect(()=>{if(demo||!authReady||(!user&&!readonly))return;run('Loading',async()=>{await load();await refresh();});},[user,authReady,demo]);
 useEffect(()=>{const check=()=>{if(document.visibilityState==='visible'&&!demo&&(user||readonly)&&Date.now()-lastRefresh.current>120000)refresh();};document.addEventListener('visibilitychange',check);return()=>document.removeEventListener('visibilitychange',check);},[demo,user]);
 useEffect(()=>{if(panel){previousFocus.current=document.activeElement;dialog.current?.showModal();}else if(dialog.current?.open){dialog.current.close();previousFocus.current?.focus();}},[panel]);
 const approved=plan?.songs.filter(s=>s.canonical).length||0;
 const openPanel=(p)=>{setError('');setCreatedLink('');setPanel(p);};
 async function showAlternatives(song){openPanel({type:'versions',song});setAlternatives([]);if(demo){setAlternatives([{videoId:'sample1',title:`${song.title} — Live performance`,channel:song.artist,reason:'Sample choice · connect YouTube for real results'}]);return;}await run('Finding live versions',async()=>setAlternatives(await request(`/plans/${plan.id}/songs/${song.id}/alternatives`,'POST',{})));}
 async function choose(song,v){await run('Saving version',async()=>{if(demo)setPlan(p=>({...p,songs:p.songs.map(s=>s.id===song.id?{...s,canonical:v}:s)}));else{await request(`/plans/${plan.id}/songs/${song.id}/version`,'POST',{videoId:v.videoId});await load(plan.id);}setPanel(null);setNotice(demo?'Sample choice saved for this preview.':'Saved as your preferred version for this song.');});}
 async function connections(){openPanel({type:'connections'});if(!demo&&user)await run('Checking connections',async()=>setServiceTypes(await request('/pco/service-types')));}
 async function sharing(){openPanel({type:'sharing'});if(!demo)await run('Loading links',async()=>setShares(await request('/shares')));}
 async function createShare(scope){await run('Creating link',async()=>{const r=await request('/shares','POST',{scope,planId:plan.id});setCreatedLink(r.url);setShares(await request('/shares'));});}
 async function openFile(song,a){const popup=window.open('about:blank','_blank');if(popup)popup.opener=null;await run('Opening attachment',async()=>{try{const prefix=readonly?`/shared/${shareMatch[2]}`:`/plans/${plan.id}`;const {url}=await request(`${prefix}/songs/${song.id}/attachments/${a.id}`,'POST',{});if(popup)popup.location=url;else{setCreatedLink(url);setNotice('Your browser blocked the new tab. Use the file link below.');}}catch(e){popup?.close();throw e;}});}
 return <><header className="header"><a href="/" className="brand"><span className="brandmark"><Radio size={24}/></span><span>gracefeed <b>worship</b></span></a><div className="header-right"><span className="church-label">FBCP <span> / </span> WORSHIP TEAM</span>{!readonly&&<button className="icon-button" aria-label="Connections" onClick={connections}><Settings2 size={20}/></button>}{user&&!readonly&&<button className="icon-button" aria-label="Sign out" onClick={()=>signOut(auth)}><LogOut size={18}/></button>}</div></header>
 <main>{demo&&<div className="sample"><span><b>Sample service</b> · Preview the experience. Your accounts are not connected.</span><button onClick={()=>configured?(setDemo(false),setPlan(null),run('Signing in',()=>signInWithPopup(auth,new GoogleAuthProvider()))):openPanel({type:'connections'})}>Connect your service <ArrowUpRight size={15}/></button></div>}
 {readonly&&<div className="sample"><span><b>Bandmate view</b> · A shared rehearsal set. No account needed.</span><span>Read only</span></div>}
 {error&&<div className="alert dismissible" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={15}/></button></div>}{notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss" onClick={()=>setNotice('')}><X size={15}/></button></div>}
 {!demo&&!readonly&&!user?<section className="welcome"><span className="eyebrow">A LITTLE LESS PREP. A LITTLE MORE MUSIC.</span><h1>Ready for Sunday.</h1><p>Your songs, live versions, rehearsal audio, and charts.<br/>One place for the whole band.</p><button className="primary" disabled={!configured||!authReady} onClick={()=>run('Signing in',()=>signInWithPopup(auth,new GoogleAuthProvider()))}><LogIn size={18}/> Sign in with Google</button><button onClick={()=>{setDemo(true);setPlan(structuredClone(demoPlan));}}>Explore a sample service <ChevronRight size={16}/></button></section>:plan?<>
 <section className="service-heading"><div><div className="eyebrow"><span className="dot"/>{readonly?'YOUR REHEARSAL SET':'LET’S GET READY FOR SUNDAY'}</div><h1>{dateLabel(plan.date)}<span className="period">.</span></h1><p>{plan.title} <span>·</span> FBCP <span>·</span> {plan.songs.length} songs</p></div><div className="heading-actions"><button disabled={!!busy} onClick={refresh}><RefreshCw size={17} className={busy==='Refreshing'?'spin':''}/>Refresh</button>{!readonly&&<button className="primary" disabled={!!busy} onClick={sharing}><Share2 size={17}/>Share with the band</button>}</div></section>
 {plan.roster?.length>0&&<section className="service-roster" aria-label="Worship team">{plan.roster.map((member,index)=><React.Fragment key={member.id||`${member.name}-${index}`}><span className="roster-member"><span aria-hidden="true">{positionEmoji(member.position)}</span> <strong>{member.name}</strong>, {member.position}</span>{index<plan.roster.length-1&&<span className="roster-divider" aria-hidden="true">|</span>}</React.Fragment>)}</section>}
 <div className="workspace"><section className="setlist"><div className="section-label"><h2>The setlist</h2><span>SERVICE ORDER</span></div>{plan.songs.map((song,i)=><article className="song" key={song.id}><span className="song-number">{String(i+1).padStart(2,'0')}</span><div className="song-content"><div className="song-top"><div><h3>{song.title}</h3><p>{song.artist||song.writers||'Artist not supplied'}</p>{!readonly&&<button className="artist-edit" onClick={()=>{setArtist(song.artist||'');openPanel({type:'artist',song});}}>{song.artist?'Edit artist':'Set artist'}</button>}</div><span className="key" title="Selected service key">{song.key}<small>KEY</small></span></div><div className="arrangement">{song.arrangement}</div><div className="version"><span className={'version-icon '+(song.canonical?'approved':'')}><Play size={15} fill="currentColor"/></span><div><span className="tiny-label">{song.canonical?(song.canonical.selection==='automatic'?'AUTOMATIC LIVE PICK':'YOUR SAVED LIVE VERSION'):'LIVE PERFORMANCE'}</span><p>{song.canonical?song.canonical.title:'Find the version you want to rehearse.'}</p>{song.canonical&&<small>{song.canonical.channel}</small>}</div>{song.canonical&&!demo&&<a className="icon-button" href={`https://www.youtube.com/watch?v=${song.canonical.videoId}`} target="_blank" rel="noreferrer" aria-label={`Watch ${song.title}`}><ArrowUpRight size={18}/></a>}</div><div className="song-actions"><button onClick={()=>openPanel({type:'files',kind:'audio',song})}><Headphones size={16}/>Audio <span className="count">{song.attachments.filter(a=>a.kind==='audio').length}</span></button><button onClick={()=>openPanel({type:'files',kind:'chart',song})}><FileText size={16}/>Charts <span className="count">{song.attachments.filter(a=>a.kind==='chart').length}</span></button>{!readonly&&<button className="text-button" disabled={!!busy} onClick={()=>showAlternatives(song)}>{song.canonical?'Show alternatives':'Choose a live version'}<ChevronRight size={15}/></button>}</div>{!readonly&&<label className="include"><input type="checkbox" checked={song.inPlaylist!==false} disabled={!!busy} onChange={e=>{const include=e.target.checked;run('Updating selection',async()=>{if(demo)setPlan(p=>({...p,songs:p.songs.map(s=>s.id===song.id?{...s,inPlaylist:include}:s)}));else{await request(`/plans/${plan.id}/songs/${song.id}/include`,'POST',{include});await load(plan.id);}});}}/> Include in rehearsal playlist</label>}</div></article>)}{!plan.songs.length&&<div className="empty">No songs yet. Refresh after Steven adds the set.</div>}</section>
 <aside><div className="playlist-card"><div className="playlist-art" aria-hidden="true"><div className="disc"><div/></div><span>FBCP<br/><b>SUNDAY<br/>SESSIONS</b></span><Music2 className="art-note" size={24}/></div><div className="playlist-body"><span className="eyebrow">LISTEN. LEARN. PLAY.</span><h2>Your rehearsal playlist</h2><p>Canonical live performances.<br/>In the order you’ll play them.</p><div className="playlist-meta"><span>{plan.date}-FBCP</span><span>{approved}/{plan.songs.length} chosen</span></div>{plan.playlistId?<a className="primary full" href={`https://www.youtube.com/playlist?list=${plan.playlistId}`} target="_blank" rel="noreferrer"><Play size={17}/>Watch playlist<ArrowUpRight size={16}/></a>:<button className="primary full" disabled><Play size={17}/>Watch playlist</button>}{!readonly&&<button className="full sync-button" disabled={!!busy||demo} onClick={()=>run('Updating playlist',async()=>{await request(`/plans/${plan.id}/playlist`,'POST',{});await load(plan.id);setNotice('Playlist updated on @richwilliamsgo.');})}>{plan.playlistId?'Update playlist':'Create playlist'}<ArrowUpRight size={16}/></button>}{plan.automation&&<p className="automation-status" role="status">{plan.automation.message}</p>}<small>{plan.playlistId&&plan.playlistDirty?'Song choices changed · automatic update pending':readonly?'Shared for your rehearsal':'YouTube destination: @richwilliamsgo'}</small></div></div><div className="prep-note"><Radio size={20}/><h3>Stay in tune with the plan.</h3><p>{status.invitationSync?'Sent invitations are checked every 15 minutes.':'Connect your Planning Center person to prepare sets when invitations arrive.'} Songs, keys, and files refresh when you open the app.</p><div className="last-sync"><span className="dot"/> {demo?'Sample data':`Checked ${new Date(plan.updatedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`}</div></div>{!readonly&&plans.length>1&&<label className="service-picker">Other services<select value={plan.id} onChange={e=>run('Loading service',()=>load(e.target.value))}>{plans.map(p=><option key={p.id} value={p.id}>{p.date} · {p.title}</option>)}</select></label>}{plan.pcoUrl&&<a className="pco-link" href={plan.pcoUrl} target="_blank" rel="noreferrer">Open in Planning Center<ArrowUpRight size={16}/></a>}</aside></div>{plan.warnings?.map((w,i)=><p className="alert" key={i}>{w}</p>)}</>:<section className="welcome"><CalendarDays size={32}/><h1>{busy?'Getting your set ready.':'Your next service starts here.'}</h1><p>{readonly?'No upcoming service is available yet. Check back after the next invitation.':'Connect Planning Center, select FBCP, then refresh your next worship plan.'}</p>{!readonly&&<button className="primary" onClick={connections}>Open connections <ArrowUpRight size={17}/></button>}<button disabled={!!busy} onClick={refresh}><RefreshCw size={17}/>Refresh</button></section>}
 <footer><span>gracefeed worship</span><span>Made for the music. Shared with the band.</span></footer></main>
 <dialog ref={dialog} onCancel={()=>setPanel(null)} onClick={e=>{if(e.target===dialog.current)setPanel(null);}}><div className="dialog-header"><span className="eyebrow">GRACEFEED WORSHIP</span><button aria-label="Close" onClick={()=>setPanel(null)}><X size={20}/></button></div>{panel?.type==='versions'&&<><h2>Find your live version.</h2><p>{panel.song.title} · {panel.song.artist}</p><p className="muted">Songwriter and original artist performances come first. Listen before saving; the service key may differ from the video.</p>{busy&&<p role="status">{busy}…</p>}{!busy&&!alternatives.length&&<p>No suitable live versions found. Check the artist details in Planning Center and try again.</p>}{alternatives.map(v=><div className="alternative" key={v.videoId}><Radio size={24}/><div><h3>{v.title}</h3><p>{v.channel}</p><small>{v.reason}</small><div className="alternative-actions">{!demo&&<a href={`https://www.youtube.com/watch?v=${v.videoId}`} target="_blank" rel="noreferrer">Watch <ArrowUpRight size={14}/></a>}<button className="primary" disabled={!!busy} onClick={()=>choose(panel.song,v)}><Check size={15}/>Use this version</button></div></div></div>)}</>}
 {panel?.type==='artist'&&<><h2>The artist you have in mind.</h2><p>{panel.song.title}</p><p className="muted">Planning Center supplies songwriters, but its Services API does not provide a dedicated artist field. Save your preferred original artist here to improve live-version searches.</p><label>Artist<input value={artist} onChange={e=>setArtist(e.target.value)} maxLength={200}/></label><button className="primary" disabled={!!busy} onClick={()=>run('Saving artist',async()=>{if(demo)setPlan(p=>({...p,songs:p.songs.map(s=>s.id===panel.song.id?{...s,artist}:s)}));else{await request(`/plans/${plan.id}/songs/${panel.song.id}/artist`,'POST',{artist});await load(plan.id);}setPanel(null);})}>Save artist</button></>}
 {panel?.type==='files'&&<><h2>{panel.kind==='audio'?'Rehearsal audio':'Charts & attachments'}</h2><p>{panel.song.title} · Key of {panel.song.key}</p>{panel.song.attachments.filter(a=>a.kind===panel.kind).map(a=><div className="file" key={a.id}><div><strong>{a.name}</strong><p>{a.steven?'Steven Braucht':'Planning Center attachment'} · {a.keyMatched?'Matched to selected key':'Check the key'}</p></div>{a.available?<button disabled={!!busy} onClick={()=>openFile(panel.song,a)}>Open<ArrowUpRight size={16}/></button>:<a href={plan.pcoUrl} target="_blank" rel="noreferrer">Planning Center<ArrowUpRight size={16}/></a>}</div>)}{!panel.song.attachments.some(a=>a.kind===panel.kind)&&<div className="empty"><Headphones size={28}/><h3>{demo?'Real files will appear here.':'No files available yet.'}</h3><p>{demo?'Connect Planning Center to see Steven’s audio and the charts for your selected key.':'Check Planning Center or refresh after the files are added.'}</p></div>}{createdLink&&<a href={createdLink} target="_blank" rel="noreferrer">Open file</a>}<p className="muted">Steven’s files are identified by his Planning Center account. Key matches come from the selected key’s attachments; other files need a quick check.</p></>}
 {panel?.type==='connections'&&<><h2>Your connections.</h2><p>One setup. Everything in one place.</p>{demo&&<div className="alert">You’re viewing a sample. The setup guide explains how to activate your Firebase and Planning Center connections.</div>}<section className="connection"><div className="connection-title"><span className="provider">PC</span><div><h3>Planning Center</h3><p>Services, selected keys, audio & charts</p></div></div><p className="muted">A Planning Center personal access token is stored securely on the server. Once installed, choose your FBCP service type below.</p><label>FBCP service type<select value={serviceType} onChange={e=>setServiceType(e.target.value)} disabled={demo}><option value="">Select your service type</option>{serviceTypes.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Your Planning Center person ID<input value={personId} onChange={e=>setPersonId(e.target.value)} placeholder="For automatic invitation checks" disabled={demo}/></label><small>With your person ID, only services with sent invitations are prepared. Leave blank to use the next plan in the service type.</small><button className="primary" disabled={demo||!!busy||!serviceType} onClick={()=>run('Saving connections',async()=>{await request('/settings','POST',{serviceTypeId:serviceType,personId});await refresh();setPanel(null);})}>Save & load service</button></section><section className="connection"><div className="connection-title"><span className="provider youtube"><Play size={21}/></span><div><h3>YouTube</h3><p>@richwilliamsgo {status.youtubeConnected?'· Connected':''}</p></div></div><button disabled={demo||!!busy} onClick={()=>run('Connecting YouTube',async()=>{const r=await request('/oauth/start','POST',{});location.assign(r.url);})}>Connect @richwilliamsgo <ArrowUpRight size={16}/></button><p className="muted">Choose your personal channel in Google. After connecting, dated playlists are created and updated automatically. Live versions are picked automatically: writers and original artists, then Bethel, then Hillsong, then other popular live recordings. Change any pick you like. Playlists are unlisted and shareable.</p></section><section className="connection"><h3>Slack is optional.</h3><p className="muted">{status.slackEnabled?'Slack is connected. Create a share link, then choose Send to Slack.':'Add a Slack incoming webhook to enable the Send to Slack button.'} No commands to remember. Notifications are sent only when you choose.</p></section></>}
 {panel?.type==='sharing'&&<><h2>A set for the whole band.</h2><p>Anyone with the link can read the set and watch its playlist. Only you can edit.</p>{demo?<div className="empty"><Share2 size={28}/><h3>Real links for real services.</h3><p>Connect your accounts to create private, revocable band links.</p></div>:<><button className="share-option" disabled={!!busy} onClick={()=>createShare('service')}><CalendarDays/><span><b>This service</b><small>{plan.date} · keeps this service’s link</small></span><ChevronRight/></button><button className="share-option" disabled={!!busy} onClick={()=>createShare('band')}><Link/><span><b>The band’s home</b><small>One stable link · always the next invited service</small></span><ChevronRight/></button>{createdLink&&<div className="created-link"><label>New share link<input readOnly value={createdLink} onFocus={e=>e.target.select()}/></label><button onClick={()=>run('Copying',async()=>{await navigator.clipboard.writeText(createdLink);setNotice('Link copied.');})}>Copy link</button>{status.slackEnabled&&<button disabled={!!busy} onClick={()=>run('Sending to Slack',async()=>{await request('/notify-slack','POST',{url:createdLink});setNotice('Rehearsal link sent to your configured Slack channel.');})}>Send this link to Slack</button>}</div>}<p className="muted">{status.shareFiles?'Downloadable files can be opened by link holders.':'Audio and charts use each bandmate’s own Planning Center login.'} Revoking a link prevents future access; previously opened files and YouTube links cannot be recalled.</p>{shares.filter(s=>!s.revoked).map(s=><div className="existing-share" key={s.id}><span>{s.scope==='band'?'Band home':`Service ${s.planId}`}<small>Link ending {s.id.slice(-6)}</small></span><button onClick={()=>run('Revoking link',async()=>{await request(`/shares/${s.id}`,'DELETE');setShares(await request('/shares'));setCreatedLink('');})}>Revoke</button></div>)}</>}</>}
 {error&&<p className="alert" role="alert">{error}</p>}</dialog>{busy&&<div className="working" role="status"><RefreshCw className="spin" size={16}/>{busy}…</div>}</>;
}
function PageGate(){
 const [unlocked,setUnlocked]=useState(()=>{try{return sessionStorage.getItem('worship-page-access')==='yes';}catch{return false;}});
 const [password,setPassword]=useState('');const [gateError,setGateError]=useState('');
 function enter(e){e.preventDefault();if(!['WORSHIP','Worship','worship'].includes(password)){setGateError('That password didn’t match. Please try again.');return;}try{sessionStorage.setItem('worship-page-access','yes');}catch{}setUnlocked(true);}
 if(unlocked)return <App/>;
 return <><header className="header"><a href="/" className="brand"><span className="brandmark"><Radio size={24}/></span><span>gracefeed <b>worship</b></span></a></header><main><section className="welcome page-gate"><span className="eyebrow">FBCP WORSHIP TEAM</span><h1>Welcome, band.</h1><p>Enter the shared password to continue.</p><form onSubmit={enter}><label htmlFor="page-password">Password<input id="page-password" type="password" autoComplete="current-password" autoFocus value={password} onChange={e=>{setPassword(e.target.value);setGateError('');}} aria-describedby={gateError?'password-error':undefined}/></label>{gateError&&<p className="alert" id="password-error" role="alert">{gateError}</p>}<button className="primary full" type="submit">Enter Worship <ChevronRight size={17}/></button></form></section></main></>;
}
createRoot(document.getElementById('root')).render(<PageGate/>);
